FROM python:3.9-slim-buster AS builder

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend ./


FROM python:3.9-slim-buster

WORKDIR /app

COPY --from=builder /app ./

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]